export * from './HomePage/Home'
export * from './GenresPage/Genres'
export * from './AllFilmsPage/AllFilms'
export * from './NotFoundPage/NotFound'
export * from './FilmDetailsPage/FilmDetails'
export * from './FilteredByGenre/FilteredByGenre'